# Generated by Django 3.1.6 on 2022-07-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients_Used',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientsName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfoNiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('mobileNo', models.CharField(max_length=11)),
                ('emailAdd', models.CharField(max_length=200)),
                ('streetAdd', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('municipal', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure_of_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Submitted_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(max_length=100)),
                ('dDescription', models.TextField(max_length=500)),
                ('dPrepTime', models.CharField(max_length=500)),
                ('dCookTime', models.CharField(max_length=500)),
                ('dYieldServing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DessertList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetbites.procedure_of_recipe')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetbites.ingredients_used')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetbites.personalinfoniuser')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetbites.submitted_recipe')),
            ],
        ),
    ]
